name: Labeler

on:
  issues:
    types: [ opened, labeled ]
  pull_request:
    types: [ opened, labeled ]
  issue_comment:
    types: [ created ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_labels:
    runs-on: ubuntu-latest
    name: add Labels
    steps:
      - uses: actions/checkout@v3
      - uses: christianvuerings/add-labels@v1
        if: |
          contains(github.event.issue.labels.*.name, 'bug') ||
          contains(github.event.pull_request.labels.*.name, 'bug')
        with:
          labels: Prio_1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
